### ISSUE TITLE
Error with strict mode

### ISSUE THREAD

**Issue by ilanbiala** [JacksonGariety/gulp-nodemon#48]
Strict mode error, not sure if it is definitely from here, but the first couple references are.

```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at /Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/utils/merge.js:26:23
    at Array.forEach (native)
    at Object.merge (/Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/utils/merge.js:25:38)
    at /Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:30:23
    at callback (/Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:137:5)
    at /Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:147:14
    at fs.js:208:20
    at /Users/Eytan/Desktop/hths-lunch/node_modules/plato/node_modules/fs-extra/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:53:5
    at /Users/Eytan/Desktop/hths-lunch/node_modules/plato/node_modules/fs-extra/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:62:5
    at OpenReq.Req.done (/Users/Eytan/Desktop/hths-lunch/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:143:5)
```

**Comment by ilanbiala** [comment]
@JacksonGariety any ideas?

**Comment by JacksonGariety** [comment]
@ilanbiala i'm working on a new version for gulp 4 compatibility. I'll include this. You may help by refactoring the `.call()` and submitting a pull

**Comment by ilanbiala** [comment]
@JacksonGariety can you link us to the version that is currently in development?

**Comment by JacksonGariety** [comment]
I'll push it tonight and post here.

**Comment by JacksonGariety** [comment]
@ilanbiala I can't reproduce this in latest. The error is coming from nodemon so I have a feeling it was fixed somewhere in the 1.3.0 update. The next gulp-nodemon version will use it.

**Comment by ilanbiala** [comment]
@JacksonGariety still getting this error with the latest version `~1.0.4`.
```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at /Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/utils/merge.js:26:23
    at Array.forEach (native)
    at Object.merge (/Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/utils/merge.js:25:38)
    at /Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:30:23
    at callback (/Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:137:5)
    at /Users/Eytan/Desktop/hths-lunch/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:147:14
    at fs.js:208:20
    at /Users/Eytan/Desktop/hths-lunch/node_modules/plato/node_modules/fs-extra/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:53:5
    at /Users/Eytan/Desktop/hths-lunch/node_modules/plato/node_modules/fs-extra/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:62:5
    at OpenReq.Req.done (/Users/Eytan/Desktop/hths-lunch/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:143:5)
```

**Comment by ilanbiala** [comment]
@JacksonGariety still getting this error, what's going on...?

**Comment by JacksonGariety** [comment]
@ilanbiala can you give me steps to reproduce it please? Anything specific in your project that may be causing the issue?

**Comment by ilanbiala** [comment]
Seems to be fixed now.
